spring:
  application:
    name: jump
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:sqlite:jump.sqlite
    driver-class-name: org.sqlite.JDBC
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: jump